Feature toolbar headline
michaelamponsah/personal-portfolio pull request #1
Opened 2022-10-27 14:08 UTC by michaelamponsah

- I have implemented the toolbar and headline sections of the personal portfolio template

2022-10-27 14:58 UTC, frank1738 requested changes
Hi @michaelamponsah , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media4.giphy.com/media/fygB3IMkpMrAaJaUzK/giphy.gif"/>

## Highlights

✅ Correct use of Github workflow
✅ No linter error
✅ README is okay
✅ Good Design 👍 



## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
     N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-27 14:58 UTC, frank1738 commented on index.html
> +  </nav>
- [ ] Kindly wrap your toolbar container in a `<header>` tag instead of a `<nav>` tag.  Typically the header tag is used as a page header, it contains the site's title or logo (or both) and the main site navigation. [Check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header) for more info.

2022-10-27 14:58 UTC, frank1738 commented on index.html
> +      </li>
- [ ] Here now you can wrap your hamburger button in a `<nav>` tag. This is for semantics reasons.

2022-10-28 08:30 UTC, TuyishimireEric approved these changes
# Status: APPROVED  :+1: :+1:  
## Hi @michaelamponsah   :hand: 

Thank you for Implementing the requested changes from the previous code reviewer :clap: 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight
- All tests are passing ✔️ 
- Correct use of GitFlow ✔️ 

![Image](https://media.giphy.com/media/qlrBlSDevEdFeW5JwV/giphy.gif)


## Optional suggestions
_Check the comments bellow_

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-28 08:30 UTC, TuyishimireEric commented on README.md
> +
- [ ] [OPTIONAL] I think it would be better to guide the users how to get started with your project in your README file for the best user experience👍
Eg: 
![image](https://user-images.githubusercontent.com/102757126/198541251-e626f1ce-be42-48f5-99cb-fb8ce8531157.png)

2022-10-28 08:30 UTC, TuyishimireEric commented on README.md
> +This project is [MIT](./LICENSE) licensed.
- [ ] [OPTIONAL] I noticed that the MIT link is broken, so I suggest adding the MIT.md file to your project 👌, 
Here is the [Micorverse Template](https://github.com/microverseinc/readme-template/blob/master/MIT.md), and remember to customize it 😉
```The MIT license gives users express permission to reuse code for any purpose, sometimes even if the code is part of proprietary software. As long as users include the original copy of the MIT license in their distribution, they can make any changes or modifications to the code to suit their own needs. 💯```

2022-10-28 08:35 UTC, michaelamponsah commented on README.md
> +This project is [MIT](./LICENSE) licensed.
Many thanks for the feedback.

2022-10-28 08:36 UTC, merged