Feature details popup window
michaelamponsah/personal-portfolio pull request #11
Opened 2022-11-16 18:27 UTC by michaelamponsah

### On this feature branch, the following changes have been implemented: 
- Implemented the functionality to generate works cards in the works `section` on the fly, using JavaScript 
- Implemented the functionality to display details of cards that have been clicked on 
- Added styling and logic to open and close pop up windows or modals

### Below is a snapshot to depict the above 

**Modal display on mobile devices**
![modal-mobile](https://user-images.githubusercontent.com/42746317/202262333-636a41fa-86d6-4c3b-9b0a-ba79a9509208.PNG)

**Modal display on large screens**
![modal-pc](https://user-images.githubusercontent.com/42746317/202262570-b1a840ac-7b66-45a3-aad9-e5e9ad95a273.PNG)

2022-11-16 19:56 UTC, aimalamiri requested changes
Hi @michaelamponsah, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![AlmostThereReachGIF](https://user-images.githubusercontent.com/34779928/191347504-9f70659c-a01f-48a1-ad46-b8722d46ffca.gif)

## Highlights

- The popup is designed very well and looks fantastic ✔️ ⭐
- Good job for using the right GitHub Flow 💯
- Awesome file organization 🗃️
- Commits are descriptive and meaningful 👍
- Linters are properly set up and passing 🟢 👍

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-16 19:56 UTC, aimalamiri commented on index.html
> +      <ul>
Good job 👌but it's required to follow the Figma template design, so here you can improve the design by making the image full-width. And also please make sure to align the contents on the screen properly. It'll make your design look much more beautiful and professional. 

Your design

![image](https://user-images.githubusercontent.com/34779928/202280128-92a68e94-0374-4f7d-9dfa-9d0593bfb1ed.png)

Original Design

![image](https://user-images.githubusercontent.com/34779928/202280074-a48d61c0-7563-4fc8-9a39-42f4ed53aa4e.png)


![image](https://user-images.githubusercontent.com/34779928/202279739-6b6866b3-bcda-47f6-ab33-72d25fe5089e.png)

2022-11-16 19:56 UTC, aimalamiri commented on index.html
> +          <button class="btn btn-outline"><a href="#">See Source <img src="./assets/images/github.svg"></a></button>
The icon and the text alignment must follow the Figma design, it looks great on the desktop screen though, but you can make it more professional for the mobile screens. So kindly make sure to fix this.

Your design

![image](https://user-images.githubusercontent.com/34779928/202280570-ad33829b-e4b5-4cd1-be94-83404a3d8891.png)

Original

![image](https://user-images.githubusercontent.com/34779928/202280628-6fcc571c-1105-43d0-b233-af7b46ebd93f.png)

2022-11-17 07:23 UTC, tufoinnkuo10 requested changes
Hi @michaelamponsah 
There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally


Required Changes ♻️
Check the comments under the review
Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-11-17 07:23 UTC, tufoinnkuo10 commented on js/worksCardData.js
> +    image: {
- [optional] maybe the previous reviewer forgot to mention this. please ensure that when the popup comes up, it should not be possible to scroll through the portfolio unless it has been closed. both mobile and desktop
- [ ] please make your mobile popup full height like in the Figma design
- [ ] please add the size of the close icon to make it more visible. kindly add for both mobile and desktop version
![Screenshot (586)_LI](https://user-images.githubusercontent.com/65298048/202381194-35f3f160-2d63-40d1-8382-6afec15ae66c.jpg)

2022-11-17 07:23 UTC, tufoinnkuo10 commented on js/worksCardData.js
> +    id: 'card-4',
- [ optional] since it was not mentioned, the `see source` and `see live` buttons should be added in the projec array as it will lead to the different project sources and live links.
- [ optional] please add the size of the `see source` and `see live` buttons for both the mobile and desktop popups

2022-11-17 13:12 UTC, fherrerao requested changes
# 🦺 🚧 🚥 CHANGES REQUIRED 🚥 🚧 🦺
#
Hi Team 💯 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![So Close Snl GIF by Saturday Night Live](https://user-images.githubusercontent.com/91301423/197784121-950974af-5415-4bf0-871b-ce226a51ace4.gif)
 ## Highlights

✔️  No linter errors.
✔️  You used the correct GitHub-Flow.
✔️  Good README
✔️  Good Commit Messages

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-17 13:12 UTC, fherrerao commented on js/cardBuilder.js
> +};
- [ ] Good job making the changes requested by the previous reviewer 💯, but he made reference to the full height based on the Figma design and not that the popup window should have the full height of the screen, please always review the original design. 🥇 I think it could be better if you use the background color and the margins between the popup window and the border of the screen. 🐰

Your design:

![image](https://user-images.githubusercontent.com/91301423/202452222-7822be4e-9442-4e97-996f-758fc00e973d.png)

Figma design:

![image](https://user-images.githubusercontent.com/91301423/202452353-7afe88ea-7aa1-48c7-bd3c-1349a8f8c367.png)

Kindly, check the margin between the popup window and the border of the screen, and please, also make the same changes in the desktop version. 🌊

2022-11-17 14:03 UTC, levy002 approved these changes
## Hello @michaelamponsah 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Status: APPROVED :fire:  :fire: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [OPTIONAL] Kindly make sure to add the opacity to the background of he popup in order to meet the provided Figma design. :wink: 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-17 14:12 UTC, merged